# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  cache_opensycl:
    uses: ./.github/workflows/linux-opensycl.yml
    with:
      clang: ${{ matrix.clang }}
      os: ${{ matrix.os }}
      cuda: ${{ matrix.cuda }}
      rocm: ${{ matrix.rocm }}
    strategy:
      matrix:
        clang: [15]
        os: [ubuntu-22.04]
        cuda: [11.0.2]
        rocm: [5.4.3]

    
