name: OpenSYCL linux pipeline

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string


   
jobs:

  cache_opensycl:
    name: cache opensycl
    runs-on: ${{ inputs.os }}

    steps:

      - uses: actions/checkout@v3

      - name: clone OpenSycl
        run: git submodule update --init sycl_compiler_gits/opensycl 

      # see opensycl workflow for steps
      - name: install dependencies
        run: |
          set +e
          brew update
          brew install cmake
          brew install libomp
          brew install boost
          set -e

      - name: configure & install OpenSycl
        run: |
          cd sycl_compiler_gits/opensycl

          OMP_ROOT=`brew list libomp | grep libomp.a | sed -E "s/\/lib\/.*//"`
          echo "OMP_ROOT=${OMP_ROOT}" >> $GITHUB_ENV

          cmake -DOpenMP_ROOT=$OMP_ROOT -DCMAKE_INSTALL_PREFIX=../../sycl_compilers/opensycl .
          make -j install
  
      - name: 'Tar opensycl'
        run: tar -cvf opensycl.tar sycl_compilers/opensycl

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: OpenSYCL_compiler-${{ inputs.os }}
          path: opensycl.tar  